// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/monc"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

var prefixLikeCacheKey = "cache:like:"

type likeModel interface {
	Insert(ctx context.Context, data *Like) error
	FindOne(ctx context.Context, id string) (*Like, error)
	Update(ctx context.Context, data *Like) error
	Delete(ctx context.Context, id string) error
}

type defaultLikeModel struct {
	conn *monc.Model
}

func newDefaultLikeModel(conn *monc.Model) *defaultLikeModel {
	return &defaultLikeModel{conn: conn}
}

func (m *defaultLikeModel) Insert(ctx context.Context, data *Like) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	key := prefixLikeCacheKey + data.ID.Hex()
	_, err := m.conn.InsertOne(ctx, key, data)
	return err
}

func (m *defaultLikeModel) FindOne(ctx context.Context, id string) (*Like, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Like
	key := prefixLikeCacheKey + id
	err = m.conn.FindOne(ctx, key, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLikeModel) Update(ctx context.Context, data *Like) error {
	data.UpdateAt = time.Now()
	key := prefixLikeCacheKey + data.ID.Hex()
	_, err := m.conn.UpdateOne(ctx, key, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return err
}

func (m *defaultLikeModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	key := prefixLikeCacheKey + id
	_, err = m.conn.DeleteOne(ctx, key, bson.M{"_id": oid})
	return err
}
